package com.smart.framework;

/*****
 * @author anjum.shrimali
 */

import java.io.IOException;

import android.app.Activity;
import android.app.Application;
import android.content.SharedPreferences;
import android.util.Log;

import com.application.configuration.ApplicationConfiguration;

//@ReportsCrashes(formKey = "dExIWHdHSmxHemNxN2IxVzdSZVJlUFE6MQ", mode = ReportingInteractionMode.TOAST,resToastText = R.string.crash_toast_text)
public class SmartApplication extends Application {

	public String APP_NAME;

	private SmartDataHelper dataHelper;

	public static SmartApplication REF_SMART_APPLICATION;

	public String SHARED_PREFERENCE;
	public String LOGFILENAME;
	private boolean isDBEnabled = false;
	private boolean isSharedPreferenceEnabled = false;
	private SharedPreferences sharedPreferences;
	public boolean attachedCrashHandler = false;
	public String securityKey = "";
	private String dbName, dbSql;
	private int dbVersion;
	private SmartVersionHandler smartVersionHandler;
	static Class<?> a = Activity.class;

	@Override
	public void onCreate() {
		super.onCreate();

		
		REF_SMART_APPLICATION = this;

		loadConfiguration();

		SmartFrameworkSecurity smartFrameworkSecurity = new SmartFrameworkSecurity(this);

		if (smartFrameworkSecurity.matchKey(securityKey)) {

			if (isSharedPreferenceEnabled) {
				sharedPreferences = getSharedPreferences(SHARED_PREFERENCE, MODE_PRIVATE);
			}

			if (isDBEnabled) {
				try {
					dataHelper = new SmartDataHelper(getApplicationContext(), dbName, dbVersion, dbSql, getSmartVersionHandler());
				} catch (IOException e) {
					e.printStackTrace();
				}
			}

		} else {
			Log.e("SmartFrameworkError", "Sorry, the security key did not match!! Please try with appropriate security key.");
			REF_SMART_APPLICATION = null;
			this.onTerminate();
		}

		// ACRA.init(this);

	}

	/**
	 * Version Handler setter for handling application database versions and
	 * providing scope for executing statements whenever the application is
	 * installed or updated.
	 * 
	 * @param smartVersionHandler
	 *            = Reference of current Version Handler interface instance.
	 */

	public void setSmartVersionHandler(SmartVersionHandler smartVersionHandler) {
		this.smartVersionHandler = smartVersionHandler;
	}

	/**
	 * Getter for SmartVersionHandler
	 * 
	 * @return = Instance of SmartVersionHandler
	 */
	public SmartVersionHandler getSmartVersionHandler() {
		return smartVersionHandler;
	}

	/**
	 * Loads configurations from ApplicationConfiguration Class.
	 */
	private void loadConfiguration() {
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		APP_NAME = applicationConfiguration.AppName(this);
		SHARED_PREFERENCE = APP_NAME;
		isDBEnabled = applicationConfiguration.IsDBEnabled();
		isSharedPreferenceEnabled = applicationConfiguration.IsSharedPreferenceEnabled();
		attachedCrashHandler = applicationConfiguration.IsCrashHandlerEnabled();
		LOGFILENAME = applicationConfiguration.CrashHandlerFileName();
		securityKey = applicationConfiguration.SecurityKey();
		dbName = applicationConfiguration.DatabaseName();
		dbSql = applicationConfiguration.DatabaseSQL();
		dbVersion = applicationConfiguration.DatabaseVersion();
		if (applicationConfiguration instanceof SmartVersionHandler) {
			smartVersionHandler = (SmartVersionHandler) applicationConfiguration;
		}
	}

	/**
	 * This method will set object of <b>SmartDataHelper</b> to framework. If
	 * not set, it will use the default created by framework itself.
	 * 
	 * @param dataHelper
	 *            = Object of SmartDataHelper class
	 */
	public void setDataHelper(SmartDataHelper dataHelper) {
		this.dataHelper = dataHelper;
	}

	/**
	 * This method will return instance of <b>SharedPreferences</b> generated by
	 * SmartFramework. Framework will use SharedPreference name as given in
	 * <b>ApplicationConfiguration</b> for generation of SharedPreference.
	 * <b>Note</b> : SharedPreference Mode will be private whenever generated by
	 * SmartFramework.
	 * 
	 * @return sharedPreferences = Instance of SharedPreferences created by
	 *         SmartFramework.
	 */
	public SharedPreferences readSharedPreferences() {
		return sharedPreferences;
	}

	/**
	 * This method will write to <b>SharedPreferences</b>.
	 * 
	 * @param key
	 *            = String <b>key</b> to store in <b>SharedPreferences</b>.
	 * @param value
	 *            = String <b>value</b> to store in <b>SharedPreferences</b>.
	 */
	public void writeSharedPreferences(String key, String value) {
		SharedPreferences.Editor editor = readSharedPreferences().edit();
		editor.putString(key, value);
		editor.commit();
	}

	/**
	 * This method will write to <b>SharedPreferences</b>.
	 * 
	 * @param key
	 *            = String <b>key</b> to store in <b>SharedPreferences</b>.
	 * @param value
	 *            = boolean <b>value</b> to store in <b>SharedPreferences</b>.
	 */
	public void writeSharedPreferences(String key, boolean value) {
		SharedPreferences.Editor editor = readSharedPreferences().edit();
		editor.putBoolean(key, value);
		editor.commit();
	}

	/**
	 * This method will write to <b>SharedPreferences</b>.
	 * 
	 * @param key
	 *            = String <b>key</b> to store in <b>SharedPreferences</b>.
	 * @param value
	 *            = float <b>value</b> to store in <b>SharedPreferences</b>.
	 */
	public void writeSharedPreferences(String key, float value) {
		SharedPreferences.Editor editor = readSharedPreferences().edit();
		editor.putFloat(key, value);
		editor.commit();
	}

	/**
	 * This method will write to <b>SharedPreferences</b>.
	 * 
	 * @param key
	 *            = String <b>key</b> to store in <b>SharedPreferences</b>.
	 * @param value
	 *            = int <b>value</b> to store in <b>SharedPreferences</b>.
	 */
	public void writeSharedPreferences(String key, int value) {
		SharedPreferences.Editor editor = readSharedPreferences().edit();
		editor.putInt(key, value);
		editor.commit();
	}

	/**
	 * This method will write to <b>SharedPreferences</b>.
	 * 
	 * @param key
	 *            = String <b>key</b> to store in <b>SharedPreferences</b>.
	 * @param value
	 *            = long <b>value</b> to store in <b>SharedPreferences</b>.
	 */
	public void writeSharedPreferences(String key, long value) {
		SharedPreferences.Editor editor = readSharedPreferences().edit();
		editor.putLong(key, value);
		editor.commit();
	}

	/**
	 * This method will return instance of <b>SmartDataHelper</b> which is
	 * currently being used by the SmartFramework.<br>
	 * This method will return <b>null</b>, if <b>isDBEnabled</b> flag is false
	 * in <b>ApplicationConfiguration</b>.
	 * 
	 * @return dataHelper = Instance of <b>SmartDataHelper</b>.
	 */
	public SmartDataHelper getDataHelper() {
		if (isDBEnabled)
			return dataHelper;
		else
			return null;
	}

	@Override
	public void onTerminate() {
		System.out.println("appdestroyed");
		if (isDBEnabled)
			dataHelper.getDB().close();
		super.onTerminate();
	}

}
